#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub enum Gemuese {
    Aubergine,
    Blumenkohl,
    GrueneBohnen,
    DickeBohnen,
    Brokkoli,
    Butterrueben,
    Champignons,
    Erbsen,
    Fenchel,
    Gruenkohl,
    Gurke,
    Kartoffeln,
    Kohlrabi,
    Kuerbis,
    Lauch,
    Fruehlingszwiebeln,
    Mais,
    Mangold,
    Karotten,
    Paprika,
    Pastinaken,
    Radieschen,
    Rosenkohl,
    RoteBeete,
    Rotkohl,
    Schwarzwurzeln,
    Spargel,
    Spinat,
    Spitzkohl,
    Staudensellerie,
    Steckrueben,
    Tomaten,
    Topinambur,
    Weisskohl,
    Wirsing,
    Zucchini,
    Zuckerschoten,
    Zwiebeln,
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub enum Obst {
    Apfel,
    Aprikose,
    Birne,
    Blaubeeren,
    Brombeeren,
    Erdbeeren,
    Himbeeren,
    Holunderbeeren,
    Johannisbeeren,
    Kirschen,
    Mirabellen,
    Pflaumen,
    Quitten,
    Rhabarber,
    Stachelbeeren,
    Wassermelone,
    Weintrauben,
    Zwetschgen,
}

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub enum Salat {
    Batavia,
    Chicoree,
    Eichblattsalat,
    Eisbergsalat,
    Endiviensalat,
    Feldsalat,
    Kopfsalat,
    LolloRosso,
    Portulak,
    Radicchio,
    Rucola,
}
